development:
  adapter: postgresql
  encoding: unicode
  database: electricstorage_dev
  pool: 5
  username: postgres
  password:	postgres

test:
  adapter: postgresql
  encoding: unicode
  database: electricstorage_test
  pool: 5
  username: postgres
  password:	postgres
